import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import { Element } from 'react-scroll';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>A Awal Hadi</title>
        <meta name="description" content="Generated by A Awal Hadi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <Element name="home">
        <Hero />
      </Element>

      <Element name="about">
        <About />
      </Element>

      <Element name="skills">
        <Skills />
      </Element>

      <Element name="projects">
        <Projects />
      </Element>

      <Element name="contact">
        <Contact />
      </Element>
      <Footer />
    </div>
  )
}
