import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import { Element } from "react-scroll";
import Favicon from "../components/Favicon";
import Header from "../components/Header";
import SkillSection from "../components/SkillSection";
import ProfessionalSkills from "../components/ProfessionalSkills";
import CurrentlyLearning from "../components/CurrentlyLearning";
import ExperienceSection from "../components/ExperienceSection";
import ProjectSection from "../components/ProjectSection";
import EducationSection from "../components/EducationSection";

export default function Home() {
  return (
    <div className="py-6 px-10 w-4/5 mt-10 mb-10">
      <Head>
        <title>A Awal Hadi</title>
        <meta name="description" content="Generated by A Awal Hadi" />
        <Favicon />
      </Head>
      {/* <Navbar /> */}
      <Hero />
      {/* <Element name="home">
        <Hero />
      </Element> */}

      {/* <Element name="about">
        <About />
      </Element> */}

      {/* <Element name="skills">
        <Skills />
      </Element> */}

      {/* <Element name="projects">
        <Projects />
      </Element> */}

      {/* <Element name="contact">
        <Contact />
      </Element> */}

      {/* detailed info */}
      <main className="flex flex-col md:flex-row gap-x-10 mt-10">
        {/* contact details */}
        <div className="w-full md:w-1/3">
          <Contact />

          {/* professional skills */}
          <ProfessionalSkills />
          {/* <Skills /> */}
          <SkillSection />
          
          
          <CurrentlyLearning />
        </div>

        {/* info */}
        <div className="w-full md:w-2/3">
          <About />

          {/* <!-- work experiences --> */}
          <ExperienceSection />

          {/* <!-- projects --> */}
          <ProjectSection />
          
          {/* <!-- education --> */}
          {/* <section>
            <h2 className="text-2xl font-semibold mb-3">Education</h2>
            <ul className="text-sm">
              <li className="mb-4">
                <p className="flex justify-between text-sm">
                  <strong className="text-base">Hello University</strong>
                  <span>2022-2019</span>
                </p>
                <p className="flex justify-between text-sm">
                  Digital marketing <small>GPA 4.0</small>
                </p>
              </li>
            </ul>
          </section> */}

          <EducationSection />
        </div>
      </main>
      <Footer />
    </div>
  );
}
